name : springpetclinic-CICD

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs on : ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: login into docker hub
        uses: docker/login-action@v2
        with:
          username: "sharathchandra007"
          password: "Sarath@18"

      - name: build and push docker image
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: "sharathchandra007/my-image:1.0"   

   
